env:
  browser: true
  es6: true
  node: true
  webextensions: true

extends:
- eslint:recommended
- plugin:react/recommended

parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    experimentalObjectRestSpread: true

root: true

rules:
  arrow-parens: off
  comma-dangle: off
  function-paren-newline: off
  guard-for-in: off
  import/no-named-as-default: off
  import/prefer-default-export: off
  linebreak-style: off
  no-multi-assign: off
  no-plusplus: off
  no-restricted-syntax: off
  no-use-before-define: off
  object-curly-newline: off
  react/prop-types: off
